package com.github.petclinicpo.tests.gw;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "PetClinicNavigation.json")
public interface PetClinicNavigation {

    @Edge()
    void e_click_home();

    @Edge()
    void e_click_vet();

    @Vertex()
    void v_HomePage();

    @Vertex()
    void v_VeterinariansPage();

    @Vertex()
    void v_ErrorPage();

    @Vertex()
    void v_FindOwnerPage();

    @Edge()
    void e_click_owner();

    @Edge()
    void e_click_error();

}
